[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "application/javascript"